### ISSUE TITLE
Feedback on the Bootstrap adder

### ISSUE THREAD

**Issue by brendanheyu** [svelte-add/svelte-add#31] opened 2021-05-05 23:20 UTC
Hi folks,

Do you think that a Bootstrap (5?)  -add is a bit passe?

From the down and dirty dev we have going on, BS5 & BS icons or fontawesome + Sass + Postcss - this combo would be a great fit?

Please don't laugh too hard :)

Thoughts?

Thanks!

**Comment by trasherdk** [comment] 2021-05-05 23:57
Should I use a framework, I'd probably go with Bootstrap 5 over Tailwind CSS.

Sass, Postcss is also a good combo.

**Comment by bato3** [comment] 2021-05-07 12:16
I suggest, that bootstrap should be meta adder, who can allow to choose vanilla or some svelte component implementation.

Also sass, postcss should be extracted to separate adders, and `Preset.apply()` in parent preset. 

BTW, I think you will need techniques for marking which presets have been introduced, because sass, postcss is required by many libraries.

**Comment by babichjacob** [comment] 2021-05-07 23:41
> I suggest, that bootstrap should be meta adder, who can allow to choose vanilla or some svelte component implementation.
> 
> Also sass, postcss should be extracted to separate adders, and `Preset.apply()` in parent preset.
> 
> BTW, I think you will need techniques for marking which presets have been introduced, because sass, postcss is required by many libraries.

See https://github.com/orgs/svelte-add/projects/1 for more information about this.

**Comment by babichjacob** [comment] 2021-09-18 23:08
This would be closed by https://github.com/svelte-add/bootstrap (published and able to be used now with `npx svelte-add@latest bootstrap` or `npm init @svelte-add/kit@latest`), but because I don't use Bootstrap, I don't know what common imports are missing from the config `svelte-add` currently generates for Bootstrap.

I will leave this issue open to gather feedback, thank you!

**Comment by manuel3108** [comment] 2021-09-19 07:25
Can confirm thats it's working in general on my end, but im also not a bootstrap user, so no idea if the current one fit

**Comment by babichjacob** [comment] 2021-09-25 17:37
Note to self:
* https://www.npmjs.com/package/svelte-bootstrapjs-action

**Comment by thoward27** [comment] 2021-10-16 13:44
Hey @manuel3108, thanks for getting back to me. Apologies if I am missing anything here, this is my first foray into svelte, npm, etc. 

So, here's what I did

```
npm init svelte@next my-app (yes to all things)
cd my-app
npm install
npm run dev
(Check that everything worked)
<CTRL-C>
npx svelte-add@latest bootstrap
npm install
npm run dev
```

At this point, I see the basic styling of bootstrap on my page! So far so good. 

Now, I want to drop in a navbar, so I went to the [docs](https://getbootstrap.com/docs/5.0/components/navbar/) and copied the very first example block (under the [Supported Content](https://getbootstrap.com/docs/5.0/components/navbar/#supported-content) heading).

I take that navbar block, and I paste it in `src/routes/__layout.svelte`, because I 
want this to be on every page, not just my index. This navbar *does not* render as I would expect.

Resulting page:

<img width="428" alt="Screen Shot 2021-10-16 at 9 41 33 AM" src="https://user-images.githubusercontent.com/15902840/137589752-f0fbe148-091f-42b6-9b14-08ed7db4eab5.png">

Now, to fix that, I add the CSS to the index

```
<!DOCTYPE html>                                
<html lang="en">                                
        <head>                                
                <meta charset="utf-8" />                                
                <link rel="icon" href="/favicon.png" />                                
                <meta name="viewport" content="width=device-width, initial-scale=1" />                                
                %svelte.head%                                
                        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">                                                                
                                 
        </head>                                
        <body>                                
                <div id="svelte">%svelte.body%</div>                                
        </body>                                
</html>                                
```

At which point, I see 

<img width="1437" alt="Screen Shot 2021-10-16 at 9 44 03 AM" src="https://user-images.githubusercontent.com/15902840/137589827-5c47bd93-ae63-46d0-bfbf-183616b6530f.png">

Which is what I want.

Now, can anyone here tell me just what I am doing wrong?

**Comment by thoward27** [comment] 2021-10-17 20:03
@manuel3108 thank you for looking at this! I ran into one more question, I cannot seem to figure out how to get bootstraps javascript imported correctly. Their documentation mentions adding an import to the app entrypoint, but that doesn't seem to actually do anything for me. Mind helping me get over this hurdle?

**Comment by rhscjohn-dev** [comment] 2021-11-26 20:29
I ran `svelte-add@lastest bootstrap --svelestrap true` and I got a strange __layout.svelte file.

```
<script>
  import "../app.scss";
  import "../app.scss";
  import "../app.scss";
</script>

<slot />
```

**Comment by babichjacob** [comment] 2021-11-26 21:03
> I ran `svelte-add@lastest bootstrap --svelestrap true` and I got a strange __layout.svelte file.
> 
> ```
> <script>
>   import "../app.scss";
>   import "../app.scss";
>   import "../app.scss";
> </script>
> 
> <slot />
> ```

I couldn't reproduce this. How did you start the project directory before giving it to `svelte-add`?

**Comment by rhscjohn-dev** [comment] 2021-11-26 21:16
> > I ran `svelte-add@lastest bootstrap --svelestrap true` and I got a strange __layout.svelte file.
> > ```
> > <script>
> >   import "../app.scss";
> >   import "../app.scss";
> >   import "../app.scss";
> > </script>
> > 
> > <slot />
> > ```
> 
> I couldn't reproduce this. How did you start the project directory before giving it to `svelte-add`?

```
npm init svelte@next sveltekit-sveltestrap
cd sveltekit-sveltestrap
npm install
```
I did have to run 'svelte-add@lastest bootstrap`  a couple of times till I got the option sveltestrap option to take.  Maybe that's the problem?  Rerunning svelte-add over and over does not cleanup properly.

My variables.scss file looks funky.
```
/* Variables and mixins declared here will be available in all other SCSS files */
/* Variables and mixins declared here will be available in all other SCSS files */
/* Variables and mixins declared here will be available in all other SCSS files */
@import "bootstrap/scss/functions"; /* Override Bootstrap's variables here */
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/functions";
/* Override Bootstrap's variables here */
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/functions";
/* Override Bootstrap's variables here */
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";
```

Try running `svelte-add@lastest bootstrap` and then come back and run `svelte-add@lastest bootstrap --svelestrap true`.

**Comment by rhscjohn-dev** [comment] 2021-12-03 22:19
Trying to use Bootstrap javascript bundle .

1st try.  Load the file in  __layout.svelte .
```
<script>
  import "../app.scss";
  import { onMount } from "svelte";
  onMount(async () => {
    import("bootstrap/dist/js/bootstrap.bundle.min.js");
  });
</script>

<slot />

```
This generated the following console error.
```
4:57:11 PM [vite] Error when evaluating SSR module /src/routes/__layout.svelte:
SyntaxError: Cannot use import statement outside a module
    at new AsyncFunction (<anonymous>)
    at instantiateModule (D:\Users\johni\Projects\sveltekit-bootstrap5\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:66543:28)
Cannot use import statement outside a module
```
I think this is because bootstrap.bundle.min.js is importing popper.js .

Maybe somebody more experienced with SvelteKit has a solution.

Moving on try # 2.  Add node-module script link in app.html right before the <body> tag. 

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="description" content="" />
    <link rel="icon" href="/favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    %svelte.head%
  </head>
  <body>
    <div id="svelte">%svelte.body%</div>
    
    <!-- works in dev but not not in preview -->
    <script src="\node_modules\bootstrap\dist\js\bootstrap.bundle.min.js"></script>
  </body>
</html>
```
This works in dev but once you build and and try preview it no longer works.   Once again, maybe somebody has a solution.

Try number 3.  Use CDN in app.html .
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="description" content="" />
    <link rel="icon" href="/favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    %svelte.head%
  </head>
  <body>
    <div id="svelte">%svelte.body%</div>
    <!-- works in dev and preview -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <!-- works in dev but not not in preview -->
    <!-- <script src="\node_modules\bootstrap\dist\js\bootstrap.bundle.min.js"></script> -->
  </body>
</html>
```

This works in both build and preview.

**Comment by rhscjohn-dev** [comment] 2021-12-04 20:52
Guide for changing or adding a new theme color with Bootstrap 5.1.

We are going to change some theme colors and also add a new theme color - accent.

All of the coding is placed in the variables.scss file.
```
/* Override and add Bootstrap's variables here */
$primary: #318ae2;
$secondary: #00ffee;
$success: #21ba45;
$danger: #be0218;
$warning: #f2c037;
$info: #31ccec;
$light: #e4f2fe;
$dark: #153fab;
$body-bg: #eef3f5;
$link-color: $secondary;
$accent: #fc4ea5; // new theme color

@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/mixins";

// add new theme color(s) to $theme-colors
$custom-theme-colors: (
  "accent": $accent,
);
$theme-colors: map-merge($theme-colors, $custom-theme-colors);
// Now propagate new theme color(s) to utility classes version 5.1
$theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value");
$utilities-colors: map-merge($utilities-colors, $theme-colors-rgb);
$utilities-text-colors: map-loop(
  $utilities-colors,
  rgba-css-var,
  "$key",
  "text"
);
$utilities-bg-colors: map-loop($utilities-colors, rgba-css-var, "$key", "bg");
```

Optional step.  Modify the app.scss file.  Make all of the existing @import lines into comment.  At the end of the file add the following line `@import "bootstrap/scss/bootstrap";` .  So far, I have not had any adverse effects by importing the bootstrap sccss files this way.

Your app.scss file should look like this.
```
/* Write your global styles here, in SCSS syntax. Variables and mixins from the src/variables.scss file are available here without importing */ /* Import only what you need from Bootstrap */
// @import "bootstrap/scss/root";
// @import "bootstrap/scss/reboot";
// @import "bootstrap/scss/type";
// @import "bootstrap/scss/accordion";
// @import "bootstrap/scss/alert";
// @import "bootstrap/scss/badge";
// @import "bootstrap/scss/breadcrumb";
// @import "bootstrap/scss/buttons";
// @import "bootstrap/scss/button-group";
// @import "bootstrap/scss/card";
// @import "bootstrap/scss/carousel";
// @import "bootstrap/scss/close";
// @import "bootstrap/scss/containers";
// @import "bootstrap/scss/dropdown";
// @import "bootstrap/scss/forms";
// @import "bootstrap/scss/grid";
// @import "bootstrap/scss/images";
// @import "bootstrap/scss/list-group";
// @import "bootstrap/scss/modal";
// @import "bootstrap/scss/nav";
// @import "bootstrap/scss/navbar";
// @import "bootstrap/scss/offcanvas";
// @import "bootstrap/scss/pagination";
// @import "bootstrap/scss/popover";
// @import "bootstrap/scss/progress";
// @import "bootstrap/scss/spinners";
// @import "bootstrap/scss/tables";
// @import "bootstrap/scss/toasts";
// @import "bootstrap/scss/tooltip";
// @import "bootstrap/scss/helpers";
// @import "bootstrap/scss/utilities";
// @import "bootstrap/scss/utilities/api";
@import "bootstrap/scss/bootstrap";
```
Now let's see the changes to the color theme in action.

For Bootstrap 5.1 replace your index.svelte file with the code below.  Bonus javascript code for activating the Bootstrap components: Popover and Tooltip  when used in a  Svelte component 
```
<script>
  import { onMount } from "svelte";
  onMount(() => {
    // if this component uses Bootsrap component - Popover
    // then you must include the code below to enable Popover
    const popoverTriggerList = [].slice.call(
      document.querySelectorAll('[data-bs-toggle="popover"]')
    );
    const popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
      return new bootstrap.Popover(popoverTriggerEl);
    });
    // if this component uses Bootsrap component - Tooltip
    // then you must include the code below to enable Tooltip
    const tooltipTriggerList = [].slice.call(
      document.querySelectorAll('[data-bs-toggle="tooltip"]')
    );
    const tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl);
    });
  });
</script>

<h1>Welcome to SvelteKit</h1>
<p>
  Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation
</p>
<!-- Use new theme color on button, text, and background-->
<div class="container py-2">
  <div class="row">
    <div class="col">
      <h2>Bootstrap 5.1 New Theme Color</h2>
      <button class="btn btn-primary">Primary</button>
      <button class="btn btn-secondary">Secondary</button>
      <button class="btn btn-accent">Accent</button>
      <button class="btn btn-success">Success</button>
      <button class="btn btn-danger">Danger</button>
      <button class="btn btn-warning">Warning</button>
      <button class="btn btn-info">Info</button>
      <button class="btn btn-dark">Dark</button>
      <span class="text-accent">Accent text</span>
      <div class="bg-accent">Accent bg</div>
    </div>
  </div>
  <!-- alert -->
  <div class="alert alert-accent" role="alert">
    A simple accent alert—check it out!
  </div>
  <!-- badge -->
  <h6>Example heading <span class="badge bg-accent">New Badge</span></h6>
  <!-- spinner -->
  <div class="spinner-border text-accent" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>
<!-- navbar -->
<nav class="navbar navbar-dark bg-accent">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        fill="currentColor"
        class="bi bi-bootstrap"
        viewBox="0 0 16 16"
      >
        <path
          d="M5.062 12h3.475c1.804 0 2.888-.908 2.888-2.396 0-1.102-.761-1.916-1.904-2.034v-.1c.832-.14 1.482-.93 1.482-1.816 0-1.3-.955-2.11-2.542-2.11H5.062V12zm1.313-4.875V4.658h1.78c.973 0 1.542.457 1.542 1.237 0 .802-.604 1.23-1.764 1.23H6.375zm0 3.762V8.162h1.822c1.236 0 1.887.463 1.887 1.348 0 .896-.627 1.377-1.811 1.377H6.375z"
        />
        <path
          d="M0 4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4zm4-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3H4z"
        />
      </svg>
      Bootstrap Nav
    </a>
  </div>
</nav>
<!-- popover -->
<div class="container py-2">
  <button
    type="button"
    class="btn btn-lg btn-danger"
    data-bs-toggle="popover"
    title="Popover title"
    data-bs-content="And here's some amazing content. It's very engaging. Right?"
    >Click to toggle popover</button
  >
</div>
<!-- tooltips -->
<div class="container py-2">
  <button
    type="button"
    class="btn btn-secondary"
    data-bs-toggle="tooltip"
    data-bs-placement="top"
    title="Tooltip on top"
  >
    Tooltip on top
  </button>
  <button
    type="button"
    class="btn btn-secondary"
    data-bs-toggle="tooltip"
    data-bs-placement="right"
    title="Tooltip on right"
  >
    Tooltip on right
  </button>
  <button
    type="button"
    class="btn btn-secondary"
    data-bs-toggle="tooltip"
    data-bs-placement="bottom"
    title="Tooltip on bottom"
  >
    Tooltip on bottom
  </button>
  <button
    type="button"
    class="btn btn-secondary"
    data-bs-toggle="tooltip"
    data-bs-placement="left"
    title="Tooltip on left"
  >
    Tooltip on left
  </button>
</div>
<!-- Button trigger modal -->
<button
  type="button"
  class="m-2 btn btn-primary"
  data-bs-toggle="modal"
  data-bs-target="#exampleModal"
>
  Launch demo modal
</button>
<!-- Modal -->
<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        />
      </div>
      <div class="modal-body">body for the modal</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
          >Close</button
        >
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
<!-- dropdown -->
<div class="dropdown  m-2">
  <button
    class="btn btn-secondary dropdown-toggle"
    type="button"
    id="dropdownMenuButton1"
    data-bs-toggle="dropdown"
    aria-expanded="false"
  >
    Dropdown button
  </button>
  <ul class="dropdown-menu " aria-labelledby="dropdownMenuButton1">
    <li class="list-group-item-accent">
      <a class="dropdown-item " href="/">Action</a>
    </li>
    <li class="list-group-item-accent">
      <a class="dropdown-item" href="/">Another action</a>
    </li>
    <li class="list-group-item-accent">
      <a class="dropdown-item" href="/">Something else here</a>
    </li>
  </ul>
</div>
```
Hopefully your screen will look something like this.

![Bootstrap 5 5 new theme color](https://user-images.githubusercontent.com/60523782/144724018-ba419517-c8e5-4eb3-95e8-8333872013d2.png)
`
For Sveltestrap replace your index.svelte file with the code below. 
```
<script>
  import {
    Alert,
    Button,
    Badge,
    Spinner,
    Navbar,
    NavbarBrand,
  } from "sveltestrap";
</script>

<h1>Welcome to SvelteKit</h1>
<p>
  Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation
</p>

<div class="container py-2">
  <div class="row">
    <div class="col">
      <h2>Bootstrap 5.1 New Theme Color</h2>
      <Button color="primary">Primary</Button>
      <Button color="secondary">Secondary</Button>
      <Button color="accent">Accent</Button>
      <Button color="success">Success</Button>
      <Button color="danger">Danger</Button>
      <Button color="warning">Warning</Button>
      <Button color="info">Info</Button>
      <Button color="dark">Dark</Button>
      <span class="text-accent">Accent text</span>
      <div class="bg-accent">Accent bg</div>
    </div>
  </div>
  <Alert color="accent" dismissible>I am an alert and I can be dismissed!</Alert
  >
  <h6>
    Heading
    <Badge color="accent">New</Badge>
  </h6>
  <Spinner color="accent" type="border" />
</div>
<Navbar color="accent" dark>
  <NavbarBrand>
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      fill="currentColor"
      class="bi bi-bootstrap"
      viewBox="0 0 16 16"
    >
      <path
        d="M5.062 12h3.475c1.804 0 2.888-.908 2.888-2.396 0-1.102-.761-1.916-1.904-2.034v-.1c.832-.14 1.482-.93 1.482-1.816 0-1.3-.955-2.11-2.542-2.11H5.062V12zm1.313-4.875V4.658h1.78c.973 0 1.542.457 1.542 1.237 0 .802-.604 1.23-1.764 1.23H6.375zm0 3.762V8.162h1.822c1.236 0 1.887.463 1.887 1.348 0 .896-.627 1.377-1.811 1.377H6.375z"
      />
      <path
        d="M0 4a4 4 0 0 1 4-4h8a4 4 0 0 1 4 4v8a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4zm4-3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V4a3 3 0 0 0-3-3H4z"
      />
    </svg>
    Bootstrap Nav
  </NavbarBrand>
</Navbar>
```
Hopefully your screen will  look like this
![Sveltestrap](https://user-images.githubusercontent.com/60523782/144724176-62d79e88-ed6e-4ac2-b47a-17474d26ca67.png)

**Comment by bato3** [comment] 2021-12-31 15:54
> Trying to use Bootstrap javascript bundle .

@rhscjohn-dev try this: https://github.com/svelte-add/svelte-add/issues/173
It looks OK, I'm test it on Popover

**Comment by unruledboy** [comment] 2022-11-07 21:04
does it include the bootstrap.js file? it does not look like it because the tabs javascript behaviour does not work (no response to clicks) according to https://getbootstrap.com/docs/5.2/components/navs-tabs/#javascript-behavior

**Comment by bato3** [comment] 2022-11-09 11:13
> does it include the bootstrap.js file?

No. You should use https://sveltestrap.js.org/?path=/story/components--get-started or dynamic import js in `onMount`

**Comment by manuel3108** [comment] 2023-12-26 10:59
Apart from this issue

> does it include the bootstrap.js file? it does not look like it because the tabs javascript behaviour does not work (no response to clicks) according to https://getbootstrap.com/docs/5.2/components/navs-tabs/#javascript-behavior

everything seems to be done here. The last open topic will be handled by #327

**Closed by manuel3108** 2023-12-26 10:59 UTC
Labels: adder:bootstrap

**Comment by edouard-claude** [comment] 2024-01-29 17:03
From [svelte-add/issues/327](https://github.com/svelte-add/svelte-add/issues/327#issuecomment-1868851277)

`npx svelte-add@latest bootstrap`

```
<script lang="ts">
	import { browser } from '$app/environment';
	onMount(async () => {
		if (!browser) return;
		await import('bootstrap');
	});
</script>
```
