### ISSUE TITLE
Undefined variable error 

### ISSUE THREAD

**Issue by turkic-dev** [svelte-add/svelte-add#222] opened 2022-07-21 15:15 UTC
I am installing for the first time but it gives this error. How can I solve it?

npm create svelte@latest .
npm i
npx svelte-add@latest bootstrap
npm i

Error: Undefined variable.
   ╷
20 │   @each $color, $value in $theme-colors-rgb {
   │                           ^^^^^^^^^^^^^^^^^
   ╵
  node_modules/bootstrap/scss/_root.scss 20:27  @import

**Comment by babichjacob** [comment] 2022-07-21 22:30
Potentially caused by https://github.com/twbs/bootstrap/issues/36785#issuecomment-1189969247

**Comment by turkic-dev** [comment] 2022-07-22 07:26
I couldn't do it. Can you help me? What do I need to do? @babichjacob

**Comment by julien-deramond** [comment] 2022-07-22 17:10
Hey @turkic-dev. You [pinged in Bootstrap repo](https://github.com/twbs/bootstrap/issues/36785#issuecomment-1192740323). I managed to reproduce your issue here.
IDK how this ecosystem works but I can see there is a `src/variables.scss` in which you can add `@import 'bootstrap/scss/maps';` which is missing (see [Lean Sass imports](https://getbootstrap.com/docs/5.2/customize/optimize/#lean-sass-imports)).
Seems to work when I add it and relaunch `npm run dev -- --open`.
Hope it can help.

**Comment by turkic-dev** [comment] 2022-07-22 17:26
It's working! Thank you so much man you saved me ^^ @julien-deramond

**Comment by babichjacob** [comment] 2022-07-22 20:52
Thank you **so** much @julien-deramond for the extra guidance on this issue! The lean Sass imports link is especially helpful since I didn't know this was documented and came up with a list of imports (and what order to do them in) on my own and ended up missing some — that's been fixed in https://github.com/svelte-add/bootstrap/commit/cf107b1c17f8c5921e51af4fb2ddbae3f1c54360.

Anyway, as it concerns this issue, thank you for the report @turkic-dev! This has been fixed in https://github.com/svelte-add/bootstrap/commit/06cd29437f44781beedb578ad81a0c05d81fb725 and published to npm in https://github.com/svelte-add/svelte-add/runs/7475220861

**Closed by babichjacob** 2022-07-22 20:52 UTC
Labels: confirmed bug, adder:bootstrap
