### ISSUE TITLE
FOUC issues when adding Tailwind to a SvelteKit skeleton

### ISSUE THREAD

**Issue by brettgoulder** [svelte-add/svelte-add#137] opened 2021-08-31 18:45 UTC
I have a flash of unstyled content whenever do a full browser refresh after adding Tailwind.

**Steps to reproduce**
1) Create a brand new SvelteKit skeleton `npm init svelte@next my-app`
2) Add Tailwind `npx svelte-add@latest tailwindcss`
3) Refresh the page

HMR works so the experience has not been _too_ bad. I suspect it might be related to https://github.com/sveltejs/kit/issues/915, but I wanted to raise the issue here to see if you had any workarounds.

**Comment by babichjacob** [comment] 2021-08-31 20:34
Yes, this is a duplicate of that issue. I have learned recently that renaming the `app.postcss` file to `app.css` makes Vite's SSR dependency loader recognize it as a stylesheet that needs to be loaded, so I'll leave this issue open because it may be best for `svelte-add` to do that since I see a lot of complaints about the FOUC in the Discord server.

**Comment by Augustin82** [comment] 2021-09-07 16:44
> Yes, this is a duplicate of that issue. I have learned recently that renaming the `app.postcss` file to `app.css` makes Vite's SSR dependency loader recognize it as a stylesheet that needs to be loaded, so I'll leave this issue open because it may be best for `svelte-add` to do that since I see a lot of complaints about the FOUC in the Discord server.

Thank you so much for that!

**Closed** 2021-09-29 18:20 UTC
Labels: enhancement, adder:postcss
