### ISSUE TITLE
vite.config.js is created despite existing vite.config.ts

### ISSUE THREAD

**Issue by shindradavid** [svelte-add/svelte-add#234] opened 2022-08-28 19:55 UTC
```
// existing vite.config.ts
import { sveltekit } from '@sveltejs/kit/vite';
import type { UserConfig } from 'vite';

const config: UserConfig = {
	plugins: [sveltekit()],
};

export default config;
```
```
// newly created vite.config.js
const config = {
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: '@use "src/lib/styles/styles.scss" as *;'  // I have modified this line
      }
    }
  }
};

export default config;
```
This creates two conflicting vite config files

**Comment by friksa** [comment] 2022-10-02 11:32
Workaround is to delete vite.config.js and update vite.config.ts to
````
import { sveltekit } from '@sveltejs/kit/vite';
import type { UserConfig } from 'vite';

const config: UserConfig = {
	plugins: [sveltekit()],
	css: {
		preprocessorOptions: {
			scss: {
				additionalData: '@use "src/variables.scss" as *;'
			}
		}
	}
};

export default config;
````

**Comment by unruledboy** [comment] 2022-11-01 21:25
Nah, with the latest version, even with @friksa 's advice, it still does not work with TypeScript. 

Can we please fix the confirmed bug? Thanks.

**Comment by Gbps** [comment] 2022-11-12 22:44
This unfortunately creates a big "huh" moment when everything breaks due to the new .js file overriding the .ts file and removing `plugins: [sveltekit()]` from the vite config.

**Comment by frogdesk** [comment] 2023-02-08 06:24
Might I suggest temporarily adding Friksa's workaround to the README here until the issue is resolved? https://github.com/svelte-add/scss

**Comment by mrwormhole** [comment] 2023-04-09 00:45
just encountered today, was really confusing as a beginner, why not delete the JS config of vite after everything is finished? it is really annoying thing during demos, did shake little bit of trust on svelte-add bulma, I believe it will be fixed hopefully soon

**Comment by manuel3108** [comment] 2023-04-09 08:13
I have created a PR for that to fix that behavior, see #257 . Interestingly, this happened only for non-kit but typescript projects. After this is merged, this shouldn't happen anymore.

For anyone who just deleted `vite.config.js`: Be careful! The original author added this intentionally so that you are able to define your variables apart from the main scss / styling. The correct way would be to copy the following code inside the your `vite.config.ts`:

```js
	css: {
		preprocessorOptions: {
			scss: {
				additionalData: '@use "src/variables.scss" as *;',
			},
		},
	},
```

just below of this statement:

```js
plugins: [svelte()],
```

so that your config should look something like 
```ts
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [svelte()],

	css: {
		preprocessorOptions: {
			scss: {
				additionalData: '@use "src/variables.scss" as *;',
			},
		},
	},
});
```

**Comment by mrwormhole** [comment] 2023-04-10 00:46
I can confirm it is happening for TS projects with scss added then I have run svelte add bulma for the first time and created vite config js and vite config ts, preprocessor should not use any prepend rule for variables.scss, app.scss should manually import variables.scss as the first line to keep everything nice and clean without additional preprocess config (which probably changes every major/minkr version)

**Comment by manuel3108** [comment] 2023-04-27 16:01
This is solved with the latest update.

**Comment by frogdesk** [comment] 2023-05-02 18:42
Does not appear to be resolved.

`[plugin:vite:css] Preprocessor dependency "sass" not found. Did you install it?`

**Comment by frogdesk** [comment] 2023-05-02 19:35
New workaround, delete the vite.config.js file that is created and change vite.config.ts to:

`import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
    plugins: [sveltekit()],
    css: {
        preprocessorOptions: {
            scss: {
                additionalData: '@use "src/variables.scss" as *;'
            }
        }
    }
});`

Thanks to H in Svelte Discord for this fix.

**Comment by manuel3108** [comment] 2023-05-03 14:45
@frogdesk Could you maybe provide me the full log output, so that I can reproduce that?

**Comment by frogdesk** [comment] 2023-05-03 23:00
I used Sveltekit app initializer to create a fresh TS project then add SCSS.

1. pnpm create svelte@latest ./
2. pnpm install
3. pnpx svelte-add@latest scss
4. pnpm install
5. pnpm run dev

Everything is successful and vite claims to be ready. However when visiting the URL it is 404.

**Closed** 2023-05-04 02:52 UTC
Labels: confirmed bug, adder:postcss, adder:scss, adder:sass, adder:coffeescript, adder:imagetools

**Comment by manuel3108** [comment] 2023-05-04 03:19
Thanks for the report.
In that case, you were directly using the `npx create svelte@latest` command. Due to recent changes in the behavior of this command, we needed to adapt.

No workarounds should be necessary at this point
