### ISSUE TITLE
bug: says to run `yarn install` while using `pnpm`

### ISSUE THREAD

**Issue by benmccann** [svelte-add/svelte-add#307] opened 2023-08-31 23:52 UTC
To reproduce:
- run `pnpm create svelte@latest myapp` and select all default options
- then run `pnpx svelte-add@latest tailwindcss`

**Comment by benmccann** [comment] 2023-09-01 21:58
oh, I wonder if maybe I hadn't run `pnpm install` yet, so there was no `pnpm-lockfile.yaml` for it to be able to tell because I just had it work correctly for me. still it's a bit weird that in that case it'd default to `yarn` rather than `npm`

**Comment by manuel3108** [comment] 2023-09-09 13:19
I can confirm and reproduce this. We are currenlty using an [external package ](https://github.com/egoist/detect-package-manager/) to detect the package manager that should be used. 

For a reason that I don't understand this package seems to be returning the most "exotic" package manager that is globally installed, if no lockfile could be detected.

During `pnpm create svelte@latest myapp` we are recomending to run `npm install` afterwards, so this is a pretty niche case overall. We will need to wait for the [upstream package](https://github.com/egoist/detect-package-manager) to resolve this or implement it on our own.

**Comment by manuel3108** [comment] 2023-09-17 07:46
Thanks for creating that upstream issue!

**Comment by manuel3108** [comment] 2024-05-10 17:32
After the rewrite, we are not using `detect-package-manager` anymore. Could you check if this issue still arises?

**Comment by benmccann** [comment] 2024-05-10 20:30
Now it asks:
```
┌  Dependencies
│
◆  Do you want to install dependencies?
│  ○ None
│  ○ npm
│  ● pnpm
│  ○ yarn
│  ○ bun
```

The wording is a bit confusing. It should probably be worded something like:
```
┌  Dependencies
│
◆  Which package manager to want to install dependencies with?
│  ○ None
│  ○ npm
│  ● pnpm
│  ○ yarn
│  ○ bun
```

I think the ideal behavior though would be to do the installation automatically if there is exactly 1 lockfile present. And if there are 0 or multiple then we could either ask the question or just print a message telling the user to install dependencies.

**Comment by manuel3108** [comment] 2024-05-11 16:45
Thanks for your feedback!

I have improved the wording with #354 as you suggested. I have additionally created #355 to install dependencies without user input, if a lockfile can be detected. 

Closing this issue here.

**Closed by manuel3108** 2024-05-11 16:45 UTC
Labels: confirmed bug, upstream
