### ISSUE TITLE
Github Actions adder

### ISSUE THREAD

**Issue by LeoDog896** [svelte-add/svelte-add#203] opened 2022-04-06 15:14 UTC
An adder for github actions -- just a new file on ./github/workflows/publish.yml: 

I have an example here: https://github.com/LeoDog896/scannable/blob/master/.github/workflows/publish.yml, but that's for a subdirectory (/demo in that case). Something like that, as well as a paramater for the repository name (if possible, grab that from git) to check if the base directory should be somewhere else (in the svelte config file, `config.paths.base`)

**Comment by babichjacob** [comment] 2022-04-07 01:05
Setting up GitHub Actions would be an option for each adder since how it's expected to work depends on the deployment target.

**Comment by babichjacob** [comment] 2022-04-07 01:06
(When we have other deployment adders, I'll apply their labels to this issue)

**Comment by LeoDog896** [comment] 2022-04-25 11:26
In that case, I think a GitHub actions option for each deployment + a standalone GitHub action for vanilla setups would be nice -- ill create an external adder.

**Comment by LeoDog896** [comment] 2022-05-07 02:59
Going to be fully honest the documentation for external adders is *very* confusing -- in that case, would it be possible for there to be a standalone Github Action for static sites, as well as sometime in the future options for github actions for other types of deployments?

**Comment by manuel3108** [comment] 2024-05-10 17:41
Duplicate of #339

**Closed by manuel3108** 2024-05-10 17:41 UTC
Labels: make a new adder
