### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by babakfp** [svelte-add/svelte-add#162] opened 2021-11-10 17:29 UTC
Hi
You can check out [this repo](https://github.com/babakfp/sveltekit-docs) to see the problem. The first time that you run it, it takes a lot of time!. If you edit the app.css, it's going to take a lot(x2) time. Sometimes that I edit the app.css, it doesn't even show the changes, so I need to reload the page and this reload takes a lot of time. And sometimes my browser just stops working for seconds...
I don't know what is the problem. It's literally unusable.
Thanks🌼

**Comment by babichjacob** [comment] 2021-11-10 17:52
`svelte-add` doesn't make that broken combination of `tailwindcss` package version and `tailwind.config.cjs` configuration. Upgrade the package version to `"next"` (3 alpha) to fix it.

You can also use any of these commands:

```sh
# Tailwind v2
npm init --yes @svelte-add/kit@latest svelte-kit-tailwind-v2 -- --with tailwindcss
# Tailwind v3
npm init --yes @svelte-add/kit@latest svelte-kit-tailwind-v3 -- --with tailwindcss --tailwindcss-v3
# Interactive process if you're unfamiliar with what options are available
npm init @svelte-add/kit@latest
```

to start a new working project.

**Comment by babakfp** [comment] 2021-11-10 18:19
```
npm init --yes @svelte-add/kit@latest svelte-kit-tailwind-v3 -- --with tailwindcss 
--tailwindcss-v3
npm ERR! Cannot read properties of null (reading 'package')
```
@babichjacob

**Comment by babichjacob** [comment] 2021-11-10 18:30
Are you on the latest version of `npm` (either `7.24.1` or `8.1.3`) and Node.js (`16.13.0`)?

**Comment by babakfp** [comment] 2021-11-10 19:30
Now it outputs this error:
```
npm init --yes @svelte-add/kit@latest svelte-kit-tailwind-v3 -- --with tailwindcss --tailwindcss-v3
➕ Svelte Add's SvelteKit app initializer (Version 2021.11.09.02)

PostCSS
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at content (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/update.js:172:21)
    at updateFile (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/update.js:32:20)
    at async updateJson (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/update.js:169:2)
    at async install (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:838:4)
    at async run (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/adders/postcss/__run.js:66:2)
    at async runAdder (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:831:2)
    at async setup (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/@svelte-add/app-initializer-tools/index.js:98:4)
    at async main (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/@svelte-add/create-kit/cli.js:5:2)
npm ERR! code 1
npm ERR! path C:\Users\babak\Desktop\~(o_o)~\_2
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-kit "svelte-kit-tailwind-v3" "--with" "tailwindcss" "--tailwindcss-v3"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\babak\AppData\Local\npm-cache\_logs\2021-11-10T19_27_20_643Z-debug.log
```

debug.log file:
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\babak\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'init',
0 verbose cli   '--yes',
0 verbose cli   '@svelte-add/kit@latest',
0 verbose cli   'svelte-kit-tailwind-v3',
0 verbose cli   '--',
0 verbose cli   '--with',
0 verbose cli   'tailwindcss',
0 verbose cli   '--tailwindcss-v3'
0 verbose cli ]
1 info using npm@8.1.3
2 info using node@v16.13.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\babak\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\babak\Desktop\~(o_o)~\_2\.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\babak\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\babak\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 timing npm:load:configload Completed in 12ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 4ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 22ms
27 http fetch GET 200 https://registry.npmjs.org/@svelte-add%2fcreate-kit 3018ms (cache revalidated)
28 timing arborist:ctor Completed in 2ms
29 timing arborist:ctor Completed in 0ms
30 timing arborist:ctor Completed in 0ms
31 timing command:init Completed in 9464ms
32 verbose stack Error: command failed
32 verbose stack     at ChildProcess.<anonymous> (C:\Users\babak\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
32 verbose stack     at ChildProcess.emit (node:events:390:28)
32 verbose stack     at maybeClose (node:internal/child_process:1064:16)
32 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
33 verbose cwd C:\Users\babak\Desktop\~(o_o)~\_2
34 verbose Windows_NT 10.0.19043
35 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\babak\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "init" "--yes" "@svelte-add/kit@latest" "svelte-kit-tailwind-v3" "--" "--with" "tailwindcss" "--tailwindcss-v3"
36 verbose node v16.13.0
37 verbose npm  v8.1.3
38 error code 1
39 error path C:\Users\babak\Desktop\~(o_o)~\_2
40 error command failed
41 error command C:\Windows\system32\cmd.exe /d /s /c create-kit "svelte-kit-tailwind-v3" "--with" "tailwindcss" "--tailwindcss-v3"
42 verbose exit 1
```

In this example, I run the cmd on a new empty project but it does the same on the [sveltekit-docs](https://github.com/babakfp/sveltekit-docs) project too.

**Comment by babakfp** [comment] 2021-11-10 19:31
> Are you on the latest version of `npm` (either `7.24.1` or `8.1.3`) and Node.js (`16.13.0`)?

Yes

**Comment by babakfp** [comment] 2021-11-24 16:45
Hi
I have a question. Right now, everyone has the same problem that I have, right?
Also, why is this happening? It's just so weird that I can't use Tailwind!.
That's all. Thanks.
@babichjacob

**Comment by babichjacob** [comment] 2021-11-25 21:09
I was only able to reproduce this on Windows and I don't know why it occurs.

Try these alternatives:

```sh
npx --yes @svelte-add/create-kit@latest svelte-kit-tailwind-v3 --with tailwindcss --tailwindcss-v3
# put -- before --with if needed

# install pnpm
pnpm init --yes @svelte-add/kit@latest svelte-kit-tailwind-v3 -- --with tailwindcss --tailwindcss-v3

pnpx --yes @svelte-add/create-kit@latest svelte-kit-tailwind-v3 --with tailwindcss --tailwindcss-v3
# put -- before --with if needed
```

**Comment by babakfp** [comment] 2021-11-25 23:41
Look what I found😄

Run this:
```
npx --yes @svelte-add/create-kit@latest svelte-kit-tailwind-v3 -- --with tailwindcss --tailwindcss-v3
```

The result:
```
➕ Svelte Add's SvelteKit app initializer (Version 2021.11.20.00)
TODO: explain this error.
```

**Comment by babichjacob** [comment] 2021-12-12 02:53
I made a change I think will help address this issue. Please try again and let me know.

Specifically from this command:
```sh
npm init --yes @svelte-add/kit@latest svelte-kit-tailwind-v3 -- --with tailwindcss
```

or this one (the interactive menus):
```sh
npm init @svelte-add/kit@latest
```

**Comment by babakfp** [comment] 2021-12-12 08:33
ERROR
```
npm init --yes @svelte-add/kit@latest svelte-kit-tailwind-v3 -- --with tailwindcss
➕ Svelte Add's SvelteKit app initializer (Version 2021.12.11.03)

PostCSS
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at content (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/update.js:172:21)
    at updateFile (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/update.js:32:20)
    at async updateJson (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/update.js:169:2)
    at async install (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:836:4)
    at async run (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/adders/postcss/__run.js:66:2)
    at async runAdder (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/svelte-add/index.js:829:2)
    at async setup (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/@svelte-add/app-initializer-tools/index.js:98:4)
    at async main (file:///C:/Users/babak/AppData/Local/npm-cache/_npx/9320fb454a84dc6d/node_modules/@svelte-add/create-kit/cli.js:5:2)

Node.js v17.2.0
npm ERR! code 1
npm ERR! path C:\Users\babak\Desktop\New folder (2)
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-kit "svelte-kit-tailwind-v3" "--with" "tailwindcss"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\babak\AppData\Local\npm-cache\_logs\2021-12-12T08_24_41_217Z-debug.log
```

NO ERROR. But Tailwind JIT doesn't work.
```
npm init @svelte-add/kit@latest
```

**Comment by babichjacob** [comment] 2021-12-12 08:34
Thank you for the information! I will look into this again when I can.

**Comment by babakfp** [comment] 2022-01-23 18:45
Hi
I think this issue needs to be closed because if I'm not mistaken, the bug was related to "--v3" option.
@babichjacob

**Comment by babichjacob** [comment] 2022-01-23 18:47
Okay! Glad to hear it was potentially fixed by https://github.com/svelte-add/svelte-add/commit/a90866c860a95f7dd68127e4f30af93ad5523deb extending the timeout. I haven't had this issue myself nor heard of any reports of it occurring again since this. Thank you!

**Closed by babichjacob** 2022-01-23 18:47 UTC
Labels: confirmed bug, initializer:kit
